# Generated by Django 4.2 on 2025-12-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                        ],
                        max_length=50,
                        verbose_name="액션",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=50, verbose_name="리소스 타입"),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="리소스 ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="발생시각"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="상세정보"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "감사 로그",
                "verbose_name_plural": "감사 로그들",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "timestamp"],
                name="audit_logs_resourc_4f6f11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="audit_logs_action_474804_idx"
            ),
        ),
    ]
