# Generated by Django 4.2 on 2025-12-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openemr_encounter_id",
                    models.CharField(
                        help_text="OpenEMR 진료 ID", max_length=100, unique=True
                    ),
                ),
                ("encounter_date", models.DateTimeField()),
                (
                    "encounter_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("prescription", models.TextField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "emr_encounters",
                "ordering": ["-encounter_date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openemr_patient_id",
                    models.CharField(
                        help_text="OpenEMR 환자 ID", max_length=100, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_home", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone_mobile",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="OpenEMR 마지막 동기화 시간"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "emr_patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["openemr_patient_id"], name="emr_patient_openemr_2e487d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="emr_patient_last_na_0f47cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["date_of_birth"], name="emr_patient_date_of_2adf87_idx"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="emr.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "encounter_date"],
                name="emr_encount_patient_2152e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["openemr_encounter_id"], name="emr_encount_openemr_1a3ee4_idx"
            ),
        ),
    ]
